[package]
name = "auto-publish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_toml = "0.11.5"
crates_io_api = "0.8.0"
dotenv = "0.15.0"
reqwest = {version ="0.11.10", features= ["blocking"]}
version-compare = "0.1.0"
json = "0.12.4"
thiserror = "1.0"
anyhow = "1.0"