[package]
name = "auto-publish"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.8.0"
version-compare = "0.1.0"
cargo_toml = "0.11.5"
